databases:
  - name: New_project
    databaseName: New_project
    user: New_project

services:
  - type: web
    name: New_project
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: New_project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
